typography_spectrum: 0.8822907393332571
color:
  brandStrength: 0.5782970923464745
  lightness: 0.8627602802589536
  saturation: 0.49097394244745374
  rhythmicContrast: 0.36871001473627985
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.3561766592320055
name: imagineXsolutions
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2f6c7a23-dfc8-4099-a591-29b044d0843b.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2f6c7a23-dfc8-4099-a591-29b044d0843b.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6ab7acee-2847-4053-8a20-01a875aa1013.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0d4e56e7-8fdf-42e6-ae08-b0b6ca68be97.png
author:
  name: MA
  email: michellealphonso@imaginexsolutions.com
  url: www.imaginexsolutions.com
title: Premium Wire Shelving Solutions
description: Grocery Retail & Display
