typography_spectrum: 0.5288058647971674
color:
  brandStrength: 0.8313309523836699
  lightness: 0.7136937458933985
  saturation: 0.5017510405787737
  rhythmicContrast: 0.7344982385323705
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
github: true
layout_spectrum: 0.28508258014105925
author:
  name: MA
  email: michellealphonso@imaginexsolutions.com
  url: www.imaginexsolutions.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0d4e56e7-8fdf-42e6-ae08-b0b6ca68be97.png
name: imagineXsolutions
navigation:
  - name: Solutions That Simplify Everyday Life
    url: 'https://www.metro.com'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6ab7acee-2847-4053-8a20-01a875aa1013.jpg
title: Premium Wire Shelving Solutions
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2f6c7a23-dfc8-4099-a591-29b044d0843b.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2f6c7a23-dfc8-4099-a591-29b044d0843b.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/fe6ae2d0-bd9c-4d8f-b7ac-e632726be9f8.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/fe6ae2d0-bd9c-4d8f-b7ac-e632726be9f8.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/eb42eb5b-518e-4ba2-8764-d7efe8d3dd3a.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/eb42eb5b-518e-4ba2-8764-d7efe8d3dd3a.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/1dd37726-fdc4-4a36-bd29-e29861c159b9.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/1dd37726-fdc4-4a36-bd29-e29861c159b9.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Grocery Retail & Display
